# Generated by Django 5.1.4 on 2025-01-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='name_game',
            field=models.TextField(max_length=100, verbose_name='Название игры'),
        ),
    ]
