# Generated by Django 5.1.4 on 2025-01-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема игры', 'verbose_name_plural': 'Темы игр'},
        ),
    ]
