# Generated by Django 5.1.4 on 2025-02-08 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_theme_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='name_game',
        ),
        migrations.RemoveField(
            model_name='games',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='number_theme',
        ),
        migrations.AddField(
            model_name='games',
            name='ans',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='games',
            name='text',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.CreateModel(
            name='GamesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.TextField(max_length=100, verbose_name='Название игры')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.theme', verbose_name='Тема игры')),
            ],
            options={
                'verbose_name': 'Список игр',
                'verbose_name_plural': 'Списки игр',
            },
        ),
        migrations.AddField(
            model_name='games',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gameslist', verbose_name='Название игры'),
        ),
    ]
