# Generated by Django 5.1.4 on 2025-02-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_games_name_game_remove_games_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gameslist', verbose_name='Название игры'),
        ),
    ]
