# Generated by Django 5.1.4 on 2025-02-15 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_games_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Questions',
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопросы игры', 'verbose_name_plural': 'Вопросы игры'},
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_team', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ответ команды')),
                ('answer_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.questions', verbose_name='Правильный ответ')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.users', verbose_name='Название команды')),
            ],
        ),
    ]
