# Generated by Django 5.1.4 on 2025-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_answers_options_remove_questions_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameslist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка'),
        ),
    ]
