# Generated by Django 5.1.4 on 2025-03-25 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_questions_num_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tour', models.IntegerField(max_length=256, verbose_name='Номер тура')),
            ],
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_right', to='core.questions', verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='core.users', verbose_name='Название команды'),
        ),
    ]
