# Generated by Django 5.1.4 on 2025-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_questions_num_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='num_tour',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Номер тура'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='num_question',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Номер вопроса'),
        ),
    ]
